name: us_states
description: Simple Dart library to deal with state names and abbreviations.
version: 1.3.0
repository: https://github.com/cameronwebbable/us_states

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  collection: ^1.15.0

dev_dependencies:
  test: ^1.21.0
  lints: ^2.0.0
