name: us_states
description: Simple Dart library to deal with state names and abbreviations.
version: 1.0.2
author: Cameron Webb <cameronw@snap-raise.com>
homepage: https://github.com/snapraise/us_states

environment:
  sdk: ">=2.1.0 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
