name: us_states
description: Simple Dart library to deal with state names and abbreviations.
version: 1.2.0
homepage: https://github.com/cameronwebbable/us_states

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
